# Generated by Django 5.0.14 on 2026-08-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=100, unique=True)),
                ('templates', models.JSONField(default=dict, help_text='{"python": "...", "javascript": "...", "csharp": "..."}')),
                ('category', models.CharField(choices=[('structure', 'Estructuras'), ('navigation', 'Navegación'), ('editing', 'Edición'), ('execution', 'Ejecución')], max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comando de Voz',
                'verbose_name_plural': 'Comandos de Voz',
                'db_table': 'voice_commands',
                'ordering': ['-priority', 'trigger'],
            },
        ),
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognized_text', models.CharField(max_length=500)),
                ('template_inserted', models.TextField(blank=True, default='')),
                ('position_before', models.IntegerField(default=0)),
                ('position_after', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('dict', 'Diccionario'), ('ai', 'IA')], default='dict', max_length=10)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_history', to='projects.project')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voice_commands.voicecommand')),
            ],
            options={
                'verbose_name': 'Historial de Comando',
                'verbose_name_plural': 'Historial de Comandos',
                'db_table': 'command_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
