# Generated by Django 5.0.14 on 2026-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], max_length=20)),
                ('code', models.TextField()),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('success', 'Éxito'), ('error', 'Error'), ('timeout', 'Timeout'), ('security_blocked', 'Bloqueado por seguridad')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Ejecución',
                'verbose_name_plural': 'Logs de Ejecución',
                'db_table': 'execution_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
